"""Backend protocol for body implementations."""

from __future__ import annotations

from typing import Protocol

from sloppy_tron.provider.contract import BodyGesture, IdleMode, JsonObject
from sloppy_tron.provider.state import TaskState


class BodyBackend(Protocol):
    """Semantic body operations required by the SLOP adapter."""

    def snapshot(self) -> JsonObject: ...

    def wake(self) -> TaskState: ...

    def sleep(self) -> TaskState: ...

    def look_at_angles(self, pan: float, tilt: float) -> TaskState: ...

    def look_at_point(self, x: float, y: float, z: float) -> TaskState: ...

    def look_toward_sound(self) -> TaskState: ...

    def gesture(self, gesture: BodyGesture) -> TaskState: ...

    def capture_frame(self) -> TaskState: ...

    def set_idle_mode(self, idle_mode: IdleMode) -> TaskState: ...

    def release_media(self) -> TaskState: ...

    def acquire_media(self) -> TaskState: ...

    def enable_motion(self) -> TaskState: ...

    def disable_motion(self) -> TaskState: ...

    def emergency_stop(self) -> TaskState: ...
